server:
  port: 8090
spring:
  datasource:
    #url: jdbc:mysql://localhost/stock
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #database-platform: org.hibernate.dialect.MySQLDialect
  #data:
   # mongodb:
    #  host: localhost
     # port: 27017
      #database: stock
